version: "3.7"
services:
  db:
    image: mysql:8.0.20
    container_name: happy_delivery_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
#    volumes:
#      - "./db_data:/var/lib/mysql:/var/lib/mysql"