spring:
  datasource:
    url: jdbc:mysql://localhost:3306/happy_delivery?characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

    flyway:
      locations: classpath:/db/migration
      baseline-on-migrate: true
      baseline-version: 0
      useMysqlMetadata: true

mybatis:
  mapper-locations: mybatis/mapper/**/*.xml