INSERT INTO restaurant_categories (category) VALUES ('JAPANESE');
INSERT INTO restaurant_categories (category) VALUES ('CHINESE');
INSERT INTO restaurant_categories (category) VALUES ('CHICKEN');
INSERT INTO restaurant_categories (category) VALUES ('KOREAN');
INSERT INTO restaurant_categories (category) VALUES ('DESSERT');
INSERT INTO restaurant_categories (category) VALUES ('SNACK');
INSERT INTO restaurant_categories (category) VALUES ('WESTERN');
INSERT INTO restaurant_categories (category) VALUES ('ASIAN');
INSERT INTO restaurant_categories (category) VALUES ('PIZZA');