INSERT INTO restaurant_categories (name) VALUES ('JAPANESE');
INSERT INTO restaurant_categories (name) VALUES ('CHINESE');
INSERT INTO restaurant_categories (name) VALUES ('CHICKEN');
INSERT INTO restaurant_categories (name) VALUES ('KOREAN');
INSERT INTO restaurant_categories (name) VALUES ('DESSERT');
INSERT INTO restaurant_categories (name) VALUES ('SNACK');
INSERT INTO restaurant_categories (name) VALUES ('WESTERN');
INSERT INTO restaurant_categories (name) VALUES ('ASIAN');
INSERT INTO restaurant_categories (name) VALUES ('PIZZA');